# Generated by Django 5.2.5 on 2025-08-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_options_alter_posttranslation_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together={('language_code', 'master'), ('language_code', 'title')},
        ),
    ]
