# Generated by Django 5.2.5 on 2025-09-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('pharmacies', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pharmacy',
            unique_together={('branch', 'tool')},
        ),
    ]
