# Generated by Django 5.2.4 on 2025-07-30 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'the field must less than  100 characters'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')])),
            ],
        ),
    ]
