# Generated by Django 5.2.5 on 2025-09-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'permissions': [('can_deleteall_branches', 'Can delete all branches')]},
        ),
    ]
