# Generated by Django 5.2.5 on 2025-09-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
