# Generated by Django 5.2.5 on 2025-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_bonus_amount_alter_bonus_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
