# Generated by Django 5.2.5 on 2025-09-13 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salaryattribute_delete_salaryattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
