# Generated by Django 5.2.4 on 2025-08-09 16:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Title is too tooo!')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=40, message='phone is too tooo!')])),
                ('job', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Job is too tooo!')])),
                ('birthday', models.DateField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Ma', 'Male'), ('Fa', 'Female')], max_length=10)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
                ('branche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branche', to='branches.branch')),
            ],
        ),
    ]
