# Generated by Django 5.2.5 on 2025-08-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
