# Generated by Django 5.2.5 on 2025-08-17 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('patients', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='branche',
        ),
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('ma', 'Male'), ('fa', 'Female')], max_length=10),
        ),
    ]
