# Generated by Django 5.2.5 on 2025-09-11 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
