# Generated by Django 5.2.5 on 2025-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_rename_amount_expense_amount_expense_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
