# Generated by Django 5.2.5 on 2025-09-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
