# Generated by Django 5.2.5 on 2025-09-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_profit_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profit',
            table='profits',
        ),
    ]
