# Generated by Django 5.2.5 on 2025-09-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_profit_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
    ]
