# Generated by Django 5.2.5 on 2025-09-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_appointment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='patients.appointment'),
        ),
    ]
