# Generated by Django 5.2.5 on 2025-09-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_profit_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='patients.appointment'),
        ),
    ]
