# Generated by Django 5.2.5 on 2025-09-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_profit_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rays', to='patients.patient')),
            ],
            options={
                'db_table': 'rays',
            },
        ),
    ]
