# Generated by Django 5.2.4 on 2025-07-30 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('brief', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Text is too long!')])),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
