# Generated by Django 5.2.5 on 2025-09-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_brief_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doctors',
        ),
    ]
