# Generated by Django 5.2.5 on 2025-09-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': [('can_deleteall_doctors', 'Can delete all doctors')]},
        ),
    ]
